<?php

namespace App\Http\Resources\Api;

use App\Http\Controllers\Api\Frontend\UploadController;
use App\Models\Address;
use App\Models\File;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Storage;

class DashboardIndexResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    //    public $with=["foo" => "bar"];
    public function toArray($request)
    {
        if ($this->files()->where('file_what', 'profile') == null) {
            return [
                'id' => $this->id,
                'name' => $this->name,
                'username' => $this->username,
                'email' => $this->email,
                'meliNumber' => $this->number_meli,
                'city' => Address::where('user_id', $this->id)->pluck('city'),
                'street' => Address::where('user_id', $this->id)->pluck('street'),
                'role' => $this->role,
            ];
        } else {
            return [
                'id' => $this->id,
                'name' => $this->name,
                'username' => $this->username,
                'email' => $this->email,
                'meliNumber' => $this->number_meli,
                'city' => Address::where('user_id', $this->id)->pluck('city'),
                'street' => Address::where('user_id', $this->id)->pluck('street'),
                'role' => $this->role,
                'avatar' => asset('storage/files/' . $this->files->where('file_what', 'profile')->pluck('file_name')[0])
            ];
        }
    }
    public function with($request)
    {
        //        return parent::with($request); // TODO: Change the autogenerated stub
        //        return [
        //            'data' => [
        //                'files' =>[
        ////                    'melFile' => $this->files()->where('')
        //                ]
        //            ]
        //        ];
    }
}
