<?php

namespace App\Http\Resources\Api;

use App\Http\Controllers\Api\Frontend\UploadController;
use App\Models\Address;
use App\Models\File;
use Illuminate\Http\Resources\Json\JsonResource;

class DashboardIndexResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
//    public $with=["foo" => "bar"];
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'username' => $this->username,
            'email' => $this->email,
            'meliNumber' => $this->number_meli,
//            'city' =>Address::where('user_id',$this->id)->pluck('city'),
            'city' =>$this->when(Address::where('user_id',$this->id)->pluck('city'),Address::where('user_id',$this->id)->pluck('city')),
            'street' => $this->when(Address::where('user_id',$this->id)->pluck('street'),Address::where('user_id',$this->id)->pluck('street')),
            'role' => $this->role,
            'files' =>$this->when($request->with==='files',FileResource::collection($this->files))
//            'files' => FileResource::collection($this->files())
//            'files' => $this->when($request->with==='articles',$this->files),
//            'files' => [
//                'meliFile' => (new UploadController)->name_file['meliFile'],
////                'centerFile' => $this->when((new UploadController)->name_file['centerFile']!=null,(new UploadController())->name_file['centerFile']),
////                'expertFile' => $this->when((new UploadController)->name_file['expertFile']!=null,(new UploadController())->name_file['expertFile']),
////                'madrakFile' => $this->when((new UploadController)->name_file['madrakFile']!=null,(new UploadController())->name_file['madrakFile']),
//            ]
        ];
    }
    public function with($request)
    {
//        return parent::with($request); // TODO: Change the autogenerated stub
//        return [
//            'data' => [
//                'files' =>[
////                    'melFile' => $this->files()->where('')
//                ]
//            ]
//        ];
    }
}
